openapi: 3.0.1
info:
  title: Playstation Store API
  description: "This is a sample Playstation Store server. \
    \ You can find out more about Country/Region at [PSN Country selector](https://www.playstation.com/country-selector/index.html).\n\n\
    \ For search all games you can use the CUSA key for regions: \n\n\
    \ * `STORE-MSF75508-FULLGAMES` for Europe.\n\n\
    \ * `STORE-MSF77008-ALLGAMES` for America.\n\n\
    \ See more usefull information at [Github](https://github.com/olegshulyakov/psn-swagger) page"
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://store.playstation.com/
tags:
  - name: Geo
    description: Geo location
  - name: Games
    description: Query JSON representation of the game from store
  - name: Search
    description: Search JSON representation of the game
  - name: Images
    description: Search JSON representation of the game
paths:
  /kamaji/api/chihiro/00_09_000/geo:
    get:
      tags:
        - Geo
      summary: Returns geo location
      responses:
        200:
          description: Success
          content: { }
        400:
          description: Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      deprecated: true
  /store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}:
    get:
      tags:
        - Games
      summary: Find game information for specific container at country/region by CUSA.
      parameters:
        - name: country
          in: path
          description: Two symbols country code to search in, i.e. 'en'
          required: true
          schema:
            type: string
        - name: language
          in: path
          description: Two symbols language code to search in, i.e. 'gb'
          required: true
          schema:
            type: string
        - name: age
          in: path
          description: User's age
          required: true
          schema:
            type: integer
            format: int32
            default: 999
        - name: cusa
          in: path
          description: CUSA code to search
          required: true
          schema:
            type: string
        - name: size
          in: query
          description: Limit result count
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 1
        - name: start
          in: query
          description: Offset
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          description: Sort by
          schema:
            type: string
            enum:
              - timestamp
              - release_date
        - name: direction
          in: query
          description: Sort at
          schema:
            type: string
            enum:
              - asc
              - desc
        - name: gameContentType
          in: query
          description: Content type
          schema:
            type: string
            enum:
              - bundles
              - games
              - timed_trials
        - name: subtitleLang
          in: query
          description: Subtitle language code or several values combined by comma, i.e.
            'en', 'en,fr'
          schema:
            type: string
        - name: releaseDate
          in: query
          description: Release date
          schema:
            type: string
            enum:
              - coming_soon
              - last_7_days
              - last_30_days
        - name: gameDemo
          in: query
          description: Is game demo
          schema:
            type: boolean
        - name: price
          in: query
          description: Price range, i.e. 100-1000
          schema:
            type: string
        - name: genre
          in: query
          description: Genre
          schema:
            type: string
            enum:
              - action
              - adult
              - adventure
              - arcade
              - brain_training
              - casual
              - educational
              - family
              - fighting
              - fitness
              - horror
              - musicrhythm
              - party
              - puzzle
              - racing
              - role_playing_games
              - shooter
              - simulation
              - simulator
              - sports
              - strategy
              - unique
        - name: topCategory
          in: query
          description: Top category
          schema:
            type: string
            enum:
              - demo
              - disc_based_game
              - downloadable_game
              - game_content
        - name: voiceLang
          in: query
          description: Voice language code or several values combined by comma, i.e.
            'en', 'en,fr'
          schema:
            type: string
        - name: game_type
          in: query
          description: Game type
          schema:
            type: string
            enum:
              - bundles
              - disc_only
              - minis
              - ps2_classics
              - ps3_full_games
              - ps4_full_games
              - ps_vita_games
              - psn_games
              - psone_classics
              - psp_games
              - vr_games
        - name: relationship
          in: query
          description: Relationship
          schema:
            type: string
            enum:
              - bundles
              - demos
              - extras
        - name: platform
          in: query
          description: Platform
          schema:
            type: string
            enum:
              - ps4
              - ps3
              - psp
              - vita
      responses:
        200:
          description: Successful operation
          content: { }
        400:
          description: Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /chihiro-api/viewfinder/{country}/{language}/{age}/{cusa}:
    get:
      tags:
        - Games
      summary: Find game information for specific container at country/region by CUSA.
      parameters:
        - name: country
          in: path
          description: Two symbols country code to search in, i.e. 'en'
          required: true
          schema:
            type: string
        - name: language
          in: path
          description: Two symbols language code to search in, i.e. 'gb'
          required: true
          schema:
            type: string
        - name: age
          in: path
          description: User's age
          required: true
          schema:
            type: integer
            format: int32
            default: 999
        - name: cusa
          in: path
          description: CUSA code to search
          required: true
          schema:
            type: string
        - name: size
          in: query
          description: Limit result count
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 1
        - name: start
          in: query
          description: Offset
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          description: Sort by
          schema:
            type: string
            enum:
              - timestamp
              - release_date
        - name: direction
          in: query
          description: Sort at
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        200:
          description: Successful operation
          content: { }
        400:
          description: Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      deprecated: true
  /store/api/chihiro/00_09_000/tumbler/{country}/{language}/{age}/{searchString}:
    get:
      tags:
        - Search
      summary: Find game information for specific container at country/region by search
        string.
      parameters:
        - name: country
          in: path
          description: Two symbols country code to search in, i.e. 'en'
          required: true
          schema:
            type: string
        - name: language
          in: path
          description: Two symbols language code to search in, i.e. 'gb'
          required: true
          schema:
            type: string
        - name: age
          in: path
          description: User's age
          required: true
          schema:
            type: integer
            format: int32
            default: 999
        - name: searchString
          in: path
          description: String to search
          required: true
          schema:
            type: string
        - name: size
          in: query
          description: Limit result count
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 1
        - name: start
          in: query
          description: Offset
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          description: Sort by
          schema:
            type: string
            enum:
              - timestamp
              - release_date
        - name: direction
          in: query
          description: Sort at
          schema:
            type: string
            enum:
              - asc
              - desc
        - name: gameContentType
          in: query
          description: Content type
          schema:
            type: string
            enum:
              - bundles
              - games
              - timed_trials
        - name: subtitleLang
          in: query
          description: Subtitle language code or several values combined by comma, i.e.
            'en', 'en,fr'
          schema:
            type: string
        - name: releaseDate
          in: query
          description: Release date
          schema:
            type: string
            enum:
              - coming_soon
              - last_7_days
              - last_30_days
        - name: gameDemo
          in: query
          description: Is game demo
          schema:
            type: boolean
        - name: price
          in: query
          description: Price range, i.e. 100-1000
          schema:
            type: string
        - name: genre
          in: query
          description: Genre
          schema:
            type: string
            enum:
              - action
              - adult
              - adventure
              - arcade
              - brain_training
              - casual
              - educational
              - family
              - fighting
              - fitness
              - horror
              - musicrhythm
              - party
              - puzzle
              - racing
              - role_playing_games
              - shooter
              - simulation
              - simulator
              - sports
              - strategy
              - unique
        - name: topCategory
          in: query
          description: Top category
          schema:
            type: string
            enum:
              - demo
              - disc_based_game
              - downloadable_game
              - game_content
        - name: voiceLang
          in: query
          description: Voice language code or several values combined by comma, i.e.
            'en', 'en,fr'
          schema:
            type: string
        - name: game_type
          in: query
          description: Game type
          schema:
            type: string
            enum:
              - bundles
              - disc_only
              - minis
              - ps2_classics
              - ps3_full_games
              - ps4_full_games
              - ps_vita_games
              - psn_games
              - psone_classics
              - psp_games
              - vr_games
        - name: relationship
          in: query
          description: Relationship
          schema:
            type: string
            enum:
              - bundles
              - demos
              - extras
        - name: platform
          in: query
          description: Platform
          schema:
            type: string
            enum:
              - ps4
              - ps3
              - psp
              - vita
      responses:
        200:
          description: Successful operation
          content: { }
        400:
          description: Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /store/api/chihiro/00_09_000/container/{country}/{language}/{age}/{cusa}/image:
    get:
      tags:
        - Images
      summary: Find game image at country/region by CUSA.
      parameters:
        - name: country
          in: path
          description: Two symbols country code to search in, i.e. 'en'
          required: true
          schema:
            type: string
        - name: language
          in: path
          description: Two symbols language code to search in, i.e. 'gb'
          required: true
          schema:
            type: string
        - name: age
          in: path
          description: User's age
          required: true
          schema:
            type: integer
            format: int32
            default: 999
        - name: cusa
          in: path
          description: CUSA code to search
          required: true
          schema:
            type: string
        - name: w
          in: query
          description: Width in px
          schema:
            minimum: 0
            type: integer
        - name: h
          in: query
          description: Height in px
          schema:
            minimum: 0
            type: integer
        - name: bg_color
          in: query
          description: Background color
          schema:
            minimum: 0
            type: integer
        - name: opacity
          in: query
          description: Opacity
          schema:
            maximum: 100
            minimum: 0
            type: integer
            default: 100
        - name: platform
          in: query
          description: Platform, i.e. 'chihiro'
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content: { }
        400:
          description: Invalid
          content:
            image/jpeg;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: No data found
          content:
            image/jpeg;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    AuthErrorResponse:
      required:
        - error
        - error_code
        - error_description
      type: object
      properties:
        error_code:
          type: integer
        error:
          type: string
        error_description:
          type: string
        docs:
          type: string
    ErrorResponse:
      required:
        - codeName
      type: object
      properties:
        codeName:
          type: string
        cause:
          type: string
        errorUUID:
          type: string
